config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  root "articles#index"
  
  resources :articles
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    belongs_to :user
    has_many :tags

    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}

    def as_json(options = {})
        super(options.merge(include: :user))
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    has_many :tags
    
    validates :username, presence: true, length: {maximum: 50},  uniqueness: true,
    format:  {with:  URI::MailTo::EMAIL_REGEXP}
    validates :email, presence: true, length: {maximum: 255}, uniqueness: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user    
        User.find_by(id: session[:user_id])  
    end

    def logged_in?
        
        !current_user.nil?  
    end

    def authorized
        redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_action :authorized, only: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))
    if @article.save
      @users= User.all
      @users.each do |user|
        if @article.body.include? "@"+(user.username)
          UserMailer.tagged_email(user,@article,current_user).deliver_now
          @article.tags.create(user_id: user.id)
        end
      end
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article =Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]


  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to '/articles'
    else
        redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/articles'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]
  
  def index
    redirect_to '/users/#{current_user.id}'
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username,        
      :password,:email))
    session[:user_id] = @user.id
    if @user.save  
      UserMailer.welcome_email(@user).deliver_now
      redirect_to '/articles'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <%= @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% if logged_in? %>
    <h1>You are Logged In, <%= current_user.username %></h1>
<%end%>

<h1>Edit Article</h1>

<%= render "form", article: @article%>
<% if logged_in? %> |
<%= link_to "Log out", logout_path, method: "delete" %>
<%end%>

app/views/articles/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Articles</title>
  </head>
  <body>

    <h1>Blogger</h1>

    <ul>
      <% @articles.each do |article| %>
        <li>
            <%= link_to article.title,article %> by <a href = "/users/<%= article.user.id %>"><%= article.user.username %></a>
        </li>
      <% end %>
    </ul>
 
    <% if logged_in? %> 
      <h3><%= current_user.username %></h3>
      <%= link_to "New_Article", new_article_path %>
      <%= link_to "Log out", logout_path, method: "delete" %>
    <% else %>
      <a href = "/welcome"> Log in/ Sign Up </a>
    <%end%>
  </body>
</html>

app/views/articles/new.html.erb
<% if logged_in? %>
    <h1>You are Logged In, <%= current_user.username %></h1>
<%end%>

<h1>New Article</h1>

<%= render "form", article: @article%>

<% if logged_in? %> |
<%= link_to "Log out", logout_path, method: "delete" %>
<%end%>

app/views/articles/show.html.erb
<% if logged_in? %>
    <h1>You are Logged In, <%= current_user.username %></h1>
<%end%>

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<% if current_user == @article.user %>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %></li>
</ul>
<%end%>
<%= user_id = @article.user.id %>
posted by <a href="/users/<%=user_id%>"><%= @article.user.username %></a>
<% if logged_in? %> |
<%= link_to "Log out", logout_path, method: "delete" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :email%><br>
  <%= f.text_field :email%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h2>blogs</h2>
<ul>
    <% @articles = Article.where(:user_id == @user.id) %>
    <% @articles.each do |article|%>
        <% if article.user == @user %>
            <li> 
                <h3><%= article.title %></h3>

                <p><%= article.body %></p>

            </li>
        <%end%>
    <%end%>
</ul>

<h2>Tagged in blogs</h2>

<ul>
    <% @tags = Tag.where(:user_id == @user.id) %>
    <% @tags.each do |tag|%>
        <% if tag.user == @user %>
            <li> 
                <h3><%= tag.article.title %></h3>

                <p><%= tag.article.body %></p>

            </li>
        <%end%>
    <%end%>
</ul>